Added setting and privacy page.
abhishek2355/Alpha_Demo pull request #2
Opened 2023-10-11 07:54 UTC by Dea523

Design setting and privacy page.

2023-10-11 08:41 UTC, omkarsantoshraut requested changes

2023-10-11 08:41 UTC, omkarsantoshraut commented on lib/setting_and_privacy_listtile_widget.dart
> +class ListTileWithIconsAndContent extends StatelessWidget {
No need for this file - We can directly use the Flutter package for this type of UI.
https://pub.dev/packages/settings_ui can you try to use it directly ?

2023-10-12 16:03 UTC, abhishek2355 approved these changes
Looking good.

2023-10-12 16:04 UTC, merged

2023-10-12 16:04 UTC, Dea523 commented on lib/setting_and_privacy_listtile_widget.dart
> +class ListTileWithIconsAndContent extends StatelessWidget {
added this pacakge. Thank you , adding this pacakage make my work easier.

2023-10-12 17:17 UTC, omkarsantoshraut commented on lib/setting_and_privacy_listtile_widget.dart
> +class ListTileWithIconsAndContent extends StatelessWidget {
Thanks for your changes.

2023-10-12 17:21 UTC, omkarsantoshraut commented on lib/setting_and_privacy_listtile_widget.dart
> +class ListTileWithIconsAndContent extends StatelessWidget {
No need of this file, right?
You could remove this one.