Single Post Image AM-111
abhishek2355/Alpha_Demo pull request #4
Opened 2023-11-06 04:27 UTC by Dea523

2023-11-06 17:47 UTC, abhishek2355 commented on lib/singlePostImage.dart
> +              Icon(Icons.arrow_back_rounded),
Add size parameter in icon -->  Icon(Icons.arrow_back_rounded, size: screenHeight * app_heights.height25), like this one, do the same in the complete file.

2023-11-06 17:48 UTC, abhishek2355 commented on lib/singlePostImage.dart
> +              Icon(Icons.arrow_back_rounded),
Do the same for the text widget also.

2023-11-06 17:59 UTC, omkarsantoshraut requested changes

2023-11-06 17:59 UTC, omkarsantoshraut commented on lib/constants/app_strings.dart
> +// const comments = "Comments";
Remove unwanted changes/comments.

2023-11-06 17:59 UTC, omkarsantoshraut commented on lib/singlePostImage.dart
> +        // mainAxisAlignment: MainAxisAlignment.start,
Remove this if it is unwanted.

2023-11-06 17:59 UTC, omkarsantoshraut commented on lib/singlePostImage.dart
> +                Icon(Icons.heart_broken),
I think we already have our widget for this - @abhishek2355 can replace with that widget before creating the final PR.

2023-11-07 04:54 UTC, Dea523 commented on lib/singlePostImage.dart
> +              Icon(Icons.arrow_back_rounded),
om i will do that

2023-11-07 04:55 UTC, Dea523 commented on lib/constants/app_strings.dart
> +// const comments = "Comments";
yes

2023-11-07 13:27 UTC, abhishek2355 approved these changes
Good

2023-11-07 13:27 UTC, merged